<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Apartment;

class ApartmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $apartments = [
            [
                'title' => 'Appartamento accogliente',
                'slug' => 'appartamento-accogliente',
                'description' => 'Questo appartamento offre un ambiente accogliente e confortevole.',
                'main_img' => 'https://www.pozzicase.it/sites/default/files/styles/immagine_teaser_casa/public/casa/thumb%20.jpg?itok=ff8V817r',
                'rooms' => 2,
                'beds' => 3,
                'bathrooms' => 1,
                'square_meters' => 80,
                'address' => 'Via Roma 123',
                'city' => 'Roma',
                'country' => 'Italia',
                'zipcode' => '00100',
                'latitude' => 41.123456,
                'longitude' => 12.345678,
                'visible' => true,
                'price' => 120.50,
                'user_id' => 1,
            ],
            [
                'title' => 'Appartamento moderno',
                'slug' => 'appartamento-moderno',
                'description' => 'Questo appartamento dal design moderno offre una vista mozzafiato sulla città.',
                'main_img' => 'https://cdn.dove.it/properties/3603/medium/IMG19.jpg',
                'rooms' => 3,
                'beds' => 4,
                'bathrooms' => 2,
                'square_meters' => 120,
                'address' => 'Via Verdi 456',
                'city' => 'Milano',
                'country' => 'Italia',
                'zipcode' => '20100',
                'latitude' => 41.987654,
                'longitude' => 12.765432,
                'visible' => true,
                'price' => 180.00,
                'user_id' => 1,
            ],
            // Appartamento 3
            [
                'title' => 'Appartamento con terrazza',
                'slug' => 'appartamento-con-terrazza',
                'description' => 'Questo appartamento dispone di una spaziosa terrazza con vista panoramica.',
                'main_img' => 'https://cdn.dove.it/properties/3603/medium/IMG19.jpg',
                'rooms' => 2,
                'beds' => 2,
                'bathrooms' => 1,
                'square_meters' => 90,
                'address' => 'Via Dante 789',
                'city' => 'Napoli',
                'country' => 'Italia',
                'zipcode' => '80100',
                'latitude' => 41.654321,
                'longitude' => 12.987654,
                'visible' => true,
                'price' => 150.50,
                'user_id' => 2,
            ],
            // Appartamento 4
            [
                'title' => 'Appartamento elegante',
                'slug' => 'appartamento-elegante',
                'description' => 'Questo appartamento elegantemente arredato offre una vista mozzafiato sul mare.',
                'main_img' => 'https://cdn.dove.it/properties/3603/medium/IMG19.jpg',
                'rooms' => 4,
                'beds' => 6,
                'bathrooms' => 3,
                'square_meters' => 150,
                'address' => 'Via Mazzini 10',
                'city' => 'Firenze',
                'country' => 'Italia',
                'zipcode' => '50100',
                'latitude' => 42.123456,
                'longitude' => 13.987654,
                'visible' => true,
                'price' => 250.00,
                'user_id' => 3,
            ],
            // Appartamento 5
            [
                'title' => 'Appartamento rustico',
                'slug' => 'appartamento-rustico',
                'description' => 'Questo appartamento dallo stile rustico è immerso nella natura e offre tranquillità e relax.',
                'main_img' => 'https://cdn.dove.it/properties/3603/medium/IMG19.jpg',
                'rooms' => 2,
                'beds' => 3,
                'bathrooms' => 1,
                'square_meters' => 100,
                'address' => 'Via Provinciale 20',
                'city' => 'Bologna',
                'country' => 'Italia',
                'zipcode' => '40100',
                'latitude' => 42.987654,
                'longitude' => 13.123456,
                'visible' => true,
                'price' => 120.50,
                'user_id' => 4,
            ],
            // Appartamento 6
            [
                'title' => 'Appartamento panoramico',
                'slug' => 'appartamento-panoramico',
                'description' => 'Questo appartamento offre una vista panoramica spettacolare sulla città e sulle montagne circostanti.',
                'main_img' => 'https://cdn.dove.it/properties/3603/medium/IMG19.jpg',
                'rooms' => 3,
                'beds' => 4,
                'bathrooms' => 2,
                'square_meters' => 110,
                'address' => 'Via Garibaldi 15',
                'city' => 'Torino',
                'country' => 'Italia',
                'zipcode' => '10100',
                'latitude' => 43.123456,
                'longitude' => 14.987654,
                'visible' => true,
                'price' => 180.00,
                'user_id' => 5,
            ],
            // Appartamento 7
            [
                'title' => 'Appartamento di lusso',
                'slug' => 'appartamento-di-lusso',
                'description' => 'Questo appartamento di lusso offre comfort e eleganza in un ambiente esclusivo.',
                'main_img' => 'https://cdn.dove.it/properties/3603/medium/IMG19.jpg',
                'rooms' => 5,
                'beds' => 8,
                'bathrooms' => 4,
                'square_meters' => 200,
                'address' => 'Via Cavour 25',
                'city' => 'Venezia',
                'country' => 'Italia',
                'zipcode' => '30100',
                'latitude' => 43.987654,
                'longitude' => 14.123456,
                'visible' => true,
                'price' => 300.00,
                'user_id' => 6,
            ],
            // Appartamento 8
            [
                'title' => 'Appartamento al mare',
                'slug' => 'appartamento-al-mare',
                'description' => 'Questo appartamento si trova a pochi passi dalla spiaggia e offre una vista incredibile sul mare.',
                'main_img' => 'https://cdn.dove.it/properties/3603/medium/IMG19.jpg',
                'rooms' => 2,
                'beds' => 4,
                'bathrooms' => 1,
                'square_meters' => 90,
                'address' => 'Via Lungomare 30',
                'city' => 'Palermo',
                'country' => 'Italia',
                'zipcode' => '90100',
                'latitude' => 44.123456,
                'longitude' => 15.987654,
                'visible' => true,
                'price' => 150.50,
                'user_id' => 7,
            ],
            // Appartamento 9
            [
                'title' => 'Appartamento in centro',
                'slug' => 'appartamento-in-centro',
                'description' => 'Questo appartamento si trova nel cuore della città ed è circondato da negozi, ristoranti e attrazioni.',
                'main_img' => 'https://cdn.dove.it/properties/3603/medium/IMG19.jpg',
                'rooms' => 1,
                'beds' => 2,
                'bathrooms' => 1,
                'square_meters' => 60,
                'address' => 'Via XX Settembre 35',
                'city' => 'Genova',
                'country' => 'Italia',
                'zipcode' => '16100',
                'latitude' => 44.987654,
                'longitude' => 15.123456,
                'visible' => true,
                'price' => 100.00,
                'user_id' => 8,
            ],
            // Appartamento 10
            [
                'title' => 'Appartamento tranquillo',
                'slug' => 'appartamento-tranquillo',
                'description' => 'Questo appartamento si trova in una zona tranquilla e offre un ambiente sereno e rilassante.',
                'main_img' => 'https://cdn.dove.it/properties/3603/medium/IMG19.jpg',
                'rooms' => 3,
                'beds' => 4,
                'bathrooms' => 2,
                'square_meters' => 100,
                'address' => 'Via Provinciale 40',
                'city' => 'Verona',
                'country' => 'Italia',
                'zipcode' => '37100',
                'latitude' => 45.123456,
                'longitude' => 16.987654,
                'visible' => true,
                'price' => 120.50,
                'user_id' => 9,
            ],
        ];

        DB::table('apartments')->insert($apartments);
    }
}